### ISSUE TITLE
Slow loading of data with `Series.new()`

### ISSUE THREAD

**Issue by ghalimi** [rapidsai/node#412]
Loading 100M numbers as Int32Series with`Series.new()` on an NVIDIA A10 (PCIe Gen4: 64 GB/s) takes approximately 5s. This translates into a theoretical bandwidth of 80MB/s, which is 800 times less than PCIe Gen4's bandwidth. Is that to be expected? And if so, are there any workarounds?

As a point of comparison, a 93MB Parquet file on local NVMe storage with approximately 1GB of uncompressed data loads in about 320ms (3.1GB/s) with `DataFrame.readParquet()`.

Another point of comparison would be the loading of 2 columns of 100M Int32 values from an Apache Arrow Table with `DataFrame.fromArrow(Arrow.tableToIPC(arrowTable))`, which takes 313ms (2.5GB/s). The IPC to DF loading takes 71ms out of these 313ms (11GB/s).

**Comment by ghalimi** [comment]
@trxcllnt Yes, I am passing a JS Array of numbers, which I assumed was massively inefficient. I made sure to run the tests several times for warm up, but I like your CUDA driver initialization trick.

Thanks a ton for all these super detailed explanations. This is really helpful. I will make some more tests over the weekend and report my results.

As a side note, I spent the whole day playing with the DataFrame API, and I must say that I am really impressed. The level of integration that you've achieved with the JavaScript stack is remarkable. Awesome work!

**Comment by ghalimi** [comment]
@trxcllnt I did the same test again with `Int32Array`, and loading time dropped from 5s to 32ms, which translates into 12.5GB/s (B as in Bytes). This is even faster than with IPC, which gave us 11GB/s. I am currently using a g5.8xlarge instance, which is probably a quarter of a g5.12xlarge instance with four GPUs. Therefore, I'm probably sharing the PCIe Gen4 (64GB/s) with three other neighbors. I'll try to run the same test on the g5.12xlarge and see what I get.

Thanks again!

PS: Sorry for the newbie mistake. Steep learning curve...

**Comment by ghalimi** [comment]
@trxcllnt Regarding your workaround with pinned memory, I'm a little bit confused: how should I populate the buffer from CPU?

**Comment by trxcllnt** [comment]
@ghalimi the `@rapidsai/cuda` package exports the [`Memory`](https://github.com/rapidsai/node/blob/498c584fa20a9e65c6fc25b08f57e39cde8c2b26/modules/cuda/src/node_cuda.ts#L475-L582) and [`MemoryView`](https://github.com/rapidsai/node/blob/498c584fa20a9e65c6fc25b08f57e39cde8c2b26/modules/cuda/src/buffer.ts#L381-L435) types to represent various flavors of buffers in CUDA (they're directly analogous to the built-in `ArrayBuffer` and `ArrayBufferView`, respectively).

Additionally the `@rapidsai/rmm` package exports an additional [`DeviceBuffer`](https://github.com/rapidsai/node/blob/498c584fa20a9e65c6fc25b08f57e39cde8c2b26/modules/rmm/src/node_rmm.ts#L199-L292) as another `Memory` implementation whose underlying device memory allocation strategy is parameterized by a [`MemoryResource`](https://github.com/rapidsai/node/blob/498c584fa20a9e65c6fc25b08f57e39cde8c2b26/modules/rmm/src/memory_resource.ts#L20-L183) (at present we only have bindings to a subset of the [total set of RMM memory resources](https://github.com/rapidsai/rmm/tree/8e5b190f32b12895f3e1a6074f492f86259e221f/include/rmm/mr/device), but we can add more).

Each `MemoryView` is a proxy that [supports subscript-indexing](https://github.com/rapidsai/node/blob/498c584fa20a9e65c6fc25b08f57e39cde8c2b26/modules/cuda/src/buffer.ts#L329-L370) and has [a basic subset](https://github.com/rapidsai/node/blob/498c584fa20a9e65c6fc25b08f57e39cde8c2b26/modules/cuda/src/buffer.ts#L182-L299) of the public `TypedArray` APIs for copying, [zero-copy] slicing, and (if possible) [exporting](https://github.com/rapidsai/node/blob/498c584fa20a9e65c6fc25b08f57e39cde8c2b26/modules/cuda/src/buffer.ts#L318-L326) for CUDA IPC. By default, all MemoryViews construct a `DeviceMemory`, but this behavior [can be overridden](https://github.com/rapidsai/node/blob/498c584fa20a9e65c6fc25b08f57e39cde8c2b26/modules/cuda/src/buffer.ts#L99-L114) as well.

So what you'd want to do is wrap a `PinnedMemory` instance in an `Int32Buffer`, then copy from the host paged memory (i.e. the underlying JS `ArrayBuffer`) into the `PinnedMemory`:

```javascript
const cuda = require('@rapidsai/cuda');
const n = 10**9;
const h_i32 = new Int32Array(n);
for (let i = -1; ++i < n; h_i32[i] = i);
const p_mem = new cuda.PinnedMemory(h_i32.byteLength);
const p_i32 = new cuda.Int32Buffer(p_mem)
p_i32.copyFrom(h_i32); // <-- cudaMemcpy(h_i32, p_i32)
```

Note: while it's possible to write values directly to the `Int32Buffer`, this *is not* recommended strategy to achieve performance (regardless of the backing `Memory` kind). Each set value incurs an expensive `cudaMemcp`, which has a constant-time overhead regardless of the data size.

<details><summary>Definitely don't do this!</summary><pre>
$ node - p << EOF<br/>const cuda = require('@rapidsai/cuda');<br/><br/>const n = 10**5;<br/>const BPE = Int32Array.BYTES_PER_ELEMENT;<br/><br/>console.log(<br/>  'n=' + n.toLocaleString() + ', ' +<br/>  'Gb=' + ((n * BPE) / (1024 ** 3)).toFixed(4).toLocaleString()<br/>);<br/><br/>const p_i32 = new cuda.Int32Buffer(new cuda.PinnedMemory(n * BPE));<br/><br/>console.time('arange (PinnedMemory)');<br/>for (let i = -1; ++i < n;) {<br/>  p_i32[i] = i; // <-- BAD!!<br/>}<br/>console.timeEnd('arange (PinnedMemory)');<br/>EOF<br/>> n=100,000, Gb=0.0004<br/>> arange (PinnedMemory): 806.876ms <---- slooooow <br/></pre></details>

<details><summary>This script compares more memory management strategies and illustrates relative strengths and weaknesses of each:</summary><pre>$ node - p &lt;&lt; EOF<br/>const rmm  = require('@rapidsai/rmm');<br/>const cuda = require('@rapidsai/cuda');<br/>const cudf = require('@rapidsai/cudf');<br/>const now  = require('perf_hooks').performance.now;<br/><br/>// Number of int32_t values to allocate<br/>const n = 10 ** 9;<br/><br/>const BPE  = Int32Array.BYTES_PER_ELEMENT;<br/>const Gb   = (n * BPE) / (1024 ** 3);<br/>const nFmt = (n, d = 2) =&gt; (n % 1 === 0 ? n : (n).toFixed(d)).toLocaleString();<br/>const time = (msg, fn) =&gt; {<br/>  const t  = now();<br/>  const r  = fn();<br/>  const dt = now() - t;<br/>  const bw = Gb / (dt / 1000);<br/>  console.log((msg ? msg + ': ' : '') + nFmt(dt) + 'ms (' + nFmt(bw) + 'Gb/s)');<br/>  return r;<br/>};<br/><br/>console.log('n=' + nFmt(n) + ', Gb=' + nFmt(Gb, 4));<br/><br/>// ensure tests don't include CUDA driver initialization time<br/>new rmm.DeviceBuffer(n).dispose();<br/><br/>// initialize RMM Memory pools<br/>const cudaMr     = new rmm.CudaMemoryResource();<br/>const cudaPoolMr = new rmm.PoolMemoryResource(<br/>  cudaMr,<br/>  4 * (1024 ** 3),  // 4GiB<br/>  8 * (1024 ** 3),  // 8GiB<br/>);<br/>const managedMr     = new rmm.ManagedMemoryResource();<br/>const managedPoolMr = new rmm.PoolMemoryResource(<br/>  managedMr,<br/>  4 * (1024 ** 3),  // 4GiB<br/>  8 * (1024 ** 3),  // 8GiB<br/>);<br/><br/>console.log('ArrayBuffer:')<br/>// 1<br/>const h_i32 = time('    malloc', () =&gt; new Int32Array(n));<br/><br/>// 2<br/>time('    arange', () =&gt; {<br/>  for (let i = -1; ++i &lt; n; h_i32[i] = i) {}<br/>});<br/><br/>// 2.a<br/>time('    Series.sequence', () =&gt; cudf.Series.sequence({init: 0, size: n}));<br/><br/>// 3<br/>const hi32_ = new Int32Array(n);<br/>time('    memcpy JS -&gt; JS', () =&gt; hi32_.set(h_i32));<br/><br/>const allocators = [<br/>  [cuda.DeviceMemory.name, (n) =&gt; new cuda.DeviceMemory(n)],<br/>  [cuda.PinnedMemory.name, (n) =&gt; new cuda.PinnedMemory(n)],<br/>  [cuda.ManagedMemory.name, (n) =&gt; new cuda.ManagedMemory(n)],<br/>  [rmm.DeviceBuffer.name + '&lt;CUDA&gt;', (n) =&gt; new rmm.DeviceBuffer(n, cudaMr)],<br/>  [rmm.DeviceBuffer.name + '&lt;Managed&gt;', (n) =&gt; new rmm.DeviceBuffer(n, managedMr)],<br/>  [rmm.DeviceBuffer.name + '&lt;Pool&lt;CUDA&gt;&gt;', (n) =&gt; new rmm.DeviceBuffer(n, cudaPoolMr)],<br/>  [rmm.DeviceBuffer.name + '&lt;Pool&lt;Managed&gt;&gt;', (n) =&gt; new rmm.DeviceBuffer(n, managedPoolMr)],<br/>];<br/><br/>cudf.scope(() =&gt; {<br/>  for (let [name, malloc] of allocators) {<br/>    console.log('\n' + name + ':');<br/><br/>    const type = ~name.indexOf('&lt;') ? name.slice(0, name.indexOf('&lt;')) : name;<br/><br/>    // 4<br/>    const m_i32 = time('    malloc', () =&gt; new cuda.Int32Buffer(malloc(n * BPE)));<br/><br/>    // 5<br/>    time('    memcpy ArrayBuffer -&gt; ' + type, () =&gt; m_i32.copyFrom(h_i32));<br/><br/>    // Make a new device buffer to copy into so the driver doesn't optimize away these memcpys<br/>    const d_i32 = new cuda.Int32Buffer(new cuda.DeviceMemory(n));<br/><br/>    // 6<br/>    time('    memcpy ' + type + ' -&gt; DeviceMemory', () =&gt; d_i32.copyFrom(m_i32));<br/><br/>    // 7<br/>    time('    memcpy ' + type + ' -&gt; ArrayBuffer', () =&gt; m_i32.copyInto(hi32_));<br/><br/>    // 8<br/>    time('    Series.new(' + name + ')', () =&gt; cudf.Series.new(m_i32));<br/>  }<br/>});<br/>EOF<br/>&gt; n=1,000,000,000, Gb=3.7253<br/>&gt; ArrayBuffer:<br/>&gt;     malloc: 3.20ms (1164.18Gb/s)<br/>&gt;     arange: 3181.87ms (1.17Gb/s)<br/>&gt;     Series.sequence: 22.17ms (168.06Gb/s)<br/>&gt;     memcpy JS -&gt; JS: 3243.40ms (1.15Gb/s)<br/>&gt; <br/>&gt; DeviceMemory:<br/>&gt;     malloc: 10.14ms (367.31Gb/s)<br/>&gt;     memcpy ArrayBuffer -&gt; DeviceMemory: 677.16ms (5.50Gb/s)<br/>&gt;     memcpy DeviceMemory -&gt; DeviceMemory: 0.17ms (22272.58Gb/s)<br/>&gt;     memcpy DeviceMemory -&gt; ArrayBuffer: 634.78ms (5.87Gb/s)<br/>&gt;     Series.new(DeviceMemory): 22.16ms (168.12Gb/s)<br/>&gt; <br/>&gt; PinnedMemory:<br/>&gt;     malloc: 1890.04ms (1.97Gb/s)<br/>&gt;     memcpy ArrayBuffer -&gt; PinnedMemory: 652.76ms (5.71Gb/s)<br/>&gt;     memcpy PinnedMemory -&gt; DeviceMemory: 82.26ms (45.29Gb/s)<br/>&gt;     memcpy PinnedMemory -&gt; ArrayBuffer: 651.14ms (5.72Gb/s)<br/>&gt;     Series.new(PinnedMemory): 332.37ms (11.21Gb/s)<br/>&gt; <br/>&gt; ManagedMemory:<br/>&gt;     malloc: 6.67ms (558.63Gb/s)<br/>&gt;     memcpy ArrayBuffer -&gt; ManagedMemory: 774.77ms (4.81Gb/s)<br/>&gt;     memcpy ManagedMemory -&gt; DeviceMemory: 3.83ms (971.76Gb/s)<br/>&gt;     memcpy ManagedMemory -&gt; ArrayBuffer: 659.80ms (5.65Gb/s)<br/>&gt;     Series.new(ManagedMemory): 22.15ms (168.18Gb/s)<br/>&gt; <br/>&gt; DeviceBuffer&lt;CUDA&gt;:<br/>&gt;     malloc: 9.00ms (413.74Gb/s)<br/>&gt;     memcpy ArrayBuffer -&gt; DeviceBuffer: 675.65ms (5.51Gb/s)<br/>&gt;     memcpy DeviceBuffer -&gt; DeviceMemory: 0.10ms (36999.82Gb/s)<br/>&gt;     memcpy DeviceBuffer -&gt; ArrayBuffer: 635.62ms (5.86Gb/s)<br/>&gt;     Series.new(DeviceBuffer&lt;CUDA&gt;): 0.27ms (13667.48Gb/s)<br/>&gt; <br/>&gt; DeviceBuffer&lt;Managed&gt;:<br/>&gt;     malloc: 1.70ms (2189.69Gb/s)<br/>&gt;     memcpy ArrayBuffer -&gt; DeviceBuffer: 898.19ms (4.15Gb/s)<br/>&gt;     memcpy DeviceBuffer -&gt; DeviceMemory: 3.89ms (957.05Gb/s)<br/>&gt;     memcpy DeviceBuffer -&gt; ArrayBuffer: 656.70ms (5.67Gb/s)<br/>&gt;     Series.new(DeviceBuffer&lt;Managed&gt;): 0.21ms (18153.73Gb/s)<br/>&gt; <br/>&gt; DeviceBuffer&lt;Pool&lt;CUDA&gt;&gt;:<br/>&gt;     malloc: 1.54ms (2416.36Gb/s)<br/>&gt;     memcpy ArrayBuffer -&gt; DeviceBuffer: 675.31ms (5.52Gb/s)<br/>&gt;     memcpy DeviceBuffer -&gt; DeviceMemory: 0.10ms (37300.27Gb/s)<br/>&gt;     memcpy DeviceBuffer -&gt; ArrayBuffer: 633.80ms (5.88Gb/s)<br/>&gt;     Series.new(DeviceBuffer&lt;Pool&lt;CUDA&gt;&gt;): 0.22ms (17093.82Gb/s)<br/>&gt; <br/>&gt; DeviceBuffer&lt;Pool&lt;Managed&gt;&gt;:<br/>&gt;     malloc: 1.65ms (2260.37Gb/s)<br/>&gt;     memcpy ArrayBuffer -&gt; DeviceBuffer: 790.43ms (4.71Gb/s)<br/>&gt;     memcpy DeviceBuffer -&gt; DeviceMemory: 4.77ms (780.27Gb/s)<br/>&gt;     memcpy DeviceBuffer -&gt; ArrayBuffer: 658.40ms (5.66Gb/s)<br/>&gt;     Series.new(DeviceBuffer&lt;Pool&lt;Managed&gt;&gt;): 0.23ms (16188.96Gb/s)<br/></pre></details>

Numbered comments in the above:
1. JS ArrayBuffer `malloc` time (this is host paged memory)
2. JS ArrayBuffer `arange` time
  a. `cudf.Series.sequence()` time
4. JS ArrayBuffer `memcpy` time
5. CUDA Memory (device, host pinned, managed, and RMM) `malloc` times
6. JS to CUDA `memcpy` times
7. CUDA to JS `memcpy` times
8. Time to create a `cudf.Series` from each of the CUDA memory types

As you can see, each type of memory has its advantages and disadvantages. The type you choose will depend on your problem and memory constraints. A few notes:
1. [Device](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#device-memory) memory (allocated via regular `cudaMalloc`) results a good baseline for the other results.
2. [Pinned](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#page-locked-host-memory) memory is slow to allocate (and a potentially scarce resource as it's limited by your OS), but fairly quick to copy to/from device.
3. [Unified](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#um-unified-memory-programming-hd) (aka [Managed](https://developer.nvidia.com/blog/unified-memory-cuda-beginners/)) memory is quicker to allocate than pinned memory, not limited by OS settings, slightly slower to copy to/from device the first time, but benefits from driver optimizations for subsequent copies.

And finally, it's worth taking a closer look at RMM's `DeviceBuffer`, because `cudf.Series` [uses](https://github.com/rapidsai/node/blob/498c584fa20a9e65c6fc25b08f57e39cde8c2b26/modules/cudf/src/column.cpp#L243) a DeviceBuffer as its internal storage:
  
1. If you create a Series with another kind of data (JS Array/ArrayBuffer/ArrayBufferView, CUDA Memory/MemoryView), the Series constructs an `rmm.DeviceBuffer` and [copies the input](https://github.com/rapidsai/node/blob/498c584fa20a9e65c6fc25b08f57e39cde8c2b26/modules/cudf/src/utilities/buffer.cpp#L181-L192) into it.
    <details><summary>This behavior is visible in the following lines from the output:</summary><pre>&gt;     memcpy DeviceMemory -&gt; DeviceMemory: 0.17ms (22272.58Gb/s)<br/>&gt;     Series.new(DeviceMemory): 22.16ms (168.12Gb/s)<br/>&gt; <br/>&gt;     memcpy PinnedMemory -&gt; DeviceMemory: 82.26ms (45.29Gb/s)<br/>&gt;     Series.new(PinnedMemory): 332.37ms (11.21Gb/s)<br/>&gt; <br/>&gt;     memcpy ManagedMemory -&gt; DeviceMemory: 3.83ms (971.76Gb/s)<br/>&gt;     Series.new(ManagedMemory): 22.15ms (168.18Gb/s)<br/></pre></details>
2. **But if you create a Series from an existing `rmm.DeviceBuffer`, Series [will use it](https://github.com/rapidsai/node/blob/498c584fa20a9e65c6fc25b08f57e39cde8c2b26/modules/cudf/src/utilities/buffer.cpp#L179-L180) directly instead of copying into a new one.**
    <details><summary>This behavior is visible in the following lines from the output:</summary><pre>&gt;     memcpy ManagedMemory -&gt; DeviceMemory: 3.83ms (971.76Gb/s)<br/>&gt;     Series.new(ManagedMemory): 22.15ms (168.18Gb/s)<br/>&gt; <br/>&gt;     memcpy DeviceBuffer -&gt; DeviceMemory: 3.89ms (957.05Gb/s)<br/>&gt;     Series.new(DeviceBuffer&lt;Managed&gt;): 0.21ms (18153.73Gb/s)<br/>&gt; <br/>&gt;     memcpy DeviceBuffer -&gt; DeviceMemory: 4.77ms (780.27Gb/s)<br/>&gt;     Series.new(DeviceBuffer&lt;Pool&lt;Managed&gt;&gt;): 0.23ms (16188.96Gb/s)<br/></pre></details>

    * The first case copies the input `ManagedMemory` to a new `rmm.DeviceBuffer`.
    * The subsequent two cases use the input DeviceBuffer (even though it's backing storage is CUDA managed memory!) zero-copy.

**Comment by ghalimi** [comment]
@trxcllnt You rock! Thank you so very much. I'll dive into this right away.

**Comment by trxcllnt** [comment]
@ghalimi Unless you're doing something like a streaming pipeline with lots of small HtoD copies, you generally shouldn't have to worry about the vagaries of pinned/managed/device memory. Instead:
1. Try to block-copy as much data as you can up-front, and be sure to use accelerated utility functions (like [`cudf.Series.sequence()`](https://rapidsai.github.io/node/classes/cudf_src.AbstractSeries.html#sequence) and [`cudf.Series.readText()`](https://rapidsai.github.io/node/classes/cudf_src.AbstractSeries.html#readText)) wherever you can.
2. Once you have something stable, experiment with [using an RMM memory resource (globally or per-device) for all allocations](https://github.com/nv-morpheus/morpheus-visualizations/blob/main/src/index.ts#L93-L98). All cuDF/cuML/cuGraph/cuSpatial routines use the `currentDeviceResource()` for their internal allocations, so doing `setCurrentDeviceResource(new PoolMemoryResource())` can dramatically improve performance across the board.

**Comment by ghalimi** [comment]
@trxcllnt That makes sense. I just ran a test on 1e9 Uint32 values, and I got it loaded with your proposed method in 235ms (17GB/s). As I'm sharing the PCI bus with three other VMs, this is exactly what I would have expected. I'll now run the test on a dedicated machine. Thanks again for your help. I can't tell you how happy this makes me.

**Comment by trxcllnt** [comment]
Oh, another one you'll probably run into is needing to use [`cudf.scope()`](https://rapidsai.github.io/node/modules/cudf_src.html#scope). Unfortunately it looks like I didn't add a docstring for it, but it's a really important function for avoiding OOM's.

Since JS is garbage collected, DataFrames/Series/DeviceBuffers aren't immediately destroyed when they go out of scope. This can lead to running out of GPU memory because v8 doesn't GC early enough (v8 does know there's some "external memory" tied to a Series, and this does cause it to GC more aggressively, it's not usually aggressive enough):

```javascript
const cudf = require('@rapidsai/cudf');
let sum = 0;
// this will OOM any GPU very quickly
for (let i = -1; ++i < 1e5;) {
  sum += cudf.Series.sequence({init: i, size: 1e3}).sum();
}
```

The solution to this is wrapping your calls in a scope:
```javascript
const cudf = require('@rapidsai/cudf');
// no OOM!
for (let i = -1; ++i < 1e5;) {
  // scope destroys any GPU memory referenced/allocated by the code inside its callback,
  // with the exception of the return value, or things in the list passed as the second arg
  sum += scope(
    () => cudf.Series.sequence({size: 1e9}).sum(),
    [/* ...external GPU resources used by code in the scope() callback... */]
  );
}
```

**Comment by ghalimi** [comment]
Great! That's going to save us a ton of headache...
